name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Build the App
        run: npm run build
      - name: Run unit tests
        run: npm run test
